version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # Configura la contraseña del usuario root
      MYSQL_DATABASE: loginsystem        # Crea la base de datos automáticamente
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: springboot_app
    ports:
      - "8080:8080"
    environment:
      RELOAD_EARTHQUAKE_CSV: "true"
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/loginsystem
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
    depends_on:
      - db
    volumes:
      - ./uploads:/app/uploads # para que persistan archivos subidos (imágenes)

volumes:
  mysql_data:
  